FROM node:16.20-alpine3.17

RUN addgroup -S appgroup && adduser -S appuser -G appgroup -s /bin/sh

WORKDIR /app

COPY package*.json ./

RUN chown -R appuser:appgroup /app && su appuser -c "npm install"
