const Joi = require('joi')
const BaseModel = require('../utils/base-model.js')

module.exports = new BaseModel('User', {
  userId: Joi.string(), //since it'd be generated by backend 
                        //TODO: maybe to be changed later? 
  userName: Joi.string().required(),
  firstName: Joi.string().required(),
  lastName: Joi.string().required(),
  password: Joi.string().required(),
  userType: Joi.string().required(),
  avatar: Joi.string().default("http://localhost:9428/api/uploads/defaultAvatar.png") 
})
