#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

IFS=$'\n'

PACKAGE_LOCK_REGEX="(^.*/package-lock\.json)|(^package-lock\.json)"
PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")

if [[ ${PACKAGES[@]} ]]; then
  for package in $PACKAGES; do
    echo "📦 $package was changed. Running npm install to update your dependencies..."
    DIR=$(dirname "$package")
    cd "$DIR" && npm install && cd - > /dev/null
  done
fi
