#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

IFS=$'\n'

PACKAGE_LOCK_REGEX="(^.*/package-lock\.json)|(^package-lock\.json)"
PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")

# For each folder that contains a package-lock.json file, run npm install
if [[ ${PACKAGES[@]} ]]; then
  for PACKAGE in $PACKAGES; do
    PACKAGE_DIR="$(dirname -- "$PACKAGE")"
    echo "📦 $package was changed. Running npm install to update your dependencies..."
    cd "$PACKAGE_DIR" && npm install
  done
fi

exit 0